============================================================================================== 
Warning! Mixing Conda and module environments may lead to corruption of the
user environment. 
We do not recommend users mixing those two environments unless absolutely
necessary. Note that 
SURF does not provide any support for Conda environment.
For more information, please refer to our software policy page:
https://servicedesk.surf.nl/wiki/display/WIKI/Software+policy+Snellius#SoftwarepolicySnellius-UseofAnacondaandMinicondaenvironmentsonSnellius 

Remember that many packages have already been installed on the system and can
be loaded using 
the 'module load <package__name>' command. If you are uncertain if a package is
already available 
on the system, please use 'module avail' or 'module spider' to search for it.
============================================================================================== 
Connected to: mongodb://localhost:27017/mongo

Databases available:
Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
  File "/home/overven/.conda/envs/searchformer/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 2372, in list_database_names
    res = self._list_databases(session, nameOnly=True, comment=comment)
  File "/home/overven/.conda/envs/searchformer/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 2321, in _list_databases
    res = admin._retryable_read_command(cmd, session=session, operation=_Op.LIST_DATABASES)
  File "/home/overven/.conda/envs/searchformer/lib/python3.10/site-packages/pymongo/synchronous/database.py", line 1067, in _retryable_read_command
    return self._client._retryable_read(_cmd, read_preference, session, operation)
  File "/home/overven/.conda/envs/searchformer/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 2041, in _retryable_read
    return self._retry_internal(
  File "/home/overven/.conda/envs/searchformer/lib/python3.10/site-packages/pymongo/_csot.py", line 125, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/overven/.conda/envs/searchformer/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 2008, in _retry_internal
    ).run()
  File "/home/overven/.conda/envs/searchformer/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 2745, in run
    return self._read() if self._is_read else self._write()
  File "/home/overven/.conda/envs/searchformer/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 2890, in _read
    self._server = self._get_server()
  File "/home/overven/.conda/envs/searchformer/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 2838, in _get_server
    return self._client._select_server(
  File "/home/overven/.conda/envs/searchformer/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py", line 1827, in _select_server
    server = topology.select_server(
  File "/home/overven/.conda/envs/searchformer/lib/python3.10/site-packages/pymongo/synchronous/topology.py", line 409, in select_server
    server = self._select_server(
  File "/home/overven/.conda/envs/searchformer/lib/python3.10/site-packages/pymongo/synchronous/topology.py", line 387, in _select_server
    servers = self.select_servers(
  File "/home/overven/.conda/envs/searchformer/lib/python3.10/site-packages/pymongo/synchronous/topology.py", line 294, in select_servers
    server_descriptions = self._select_servers_loop(
  File "/home/overven/.conda/envs/searchformer/lib/python3.10/site-packages/pymongo/synchronous/topology.py", line 344, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 689bac00b23595b760c81445, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>

JOB STATISTICS
==============
Job ID: 14040891
Cluster: snellius
User/Group: overven/overven
State: RUNNING
Nodes: 1
Cores per node: 9
CPU Utilized: 00:00:00
CPU Efficiency: 0.00% of 00:05:51 core-walltime
Job Wall-clock time: 00:00:39
Memory Utilized: 0.00 MB
Memory Efficiency: 0.00% of 60.00 GB (60.00 GB/node)
WARNING: Efficiency statistics can only be obtained after the job has ended as seff tool is based on the accounting database data.
